# Generated by Django 6.0.2 on 2026-02-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0002_utilisateur_magasin_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='contact',
            new_name='prenom',
        ),
        migrations.AlterUniqueTogether(
            name='achat',
            unique_together={('magasin', 'numero_facture')},
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('magasin', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='vente',
            unique_together={('magasin', 'numero_facture')},
        ),
    ]
