# Generated by Django 6.0.2 on 2026-02-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0003_rename_contact_fournisseur_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
