# Generated by Django 6.0.2 on 2026-02-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0004_alter_achat_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
