# Generated by Django 6.0.2 on 2026-03-01 05:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0005_alter_vente_remise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achat',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterUniqueTogether(
            name='achat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='achat',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarcher.fournisseur'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='achat',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supermarcher.produit'),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='quantite',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vente',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vente',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.UniqueConstraint(fields=('magasin', 'numero_facture'), name='unique_facture_par_magasin'),
        ),
        migrations.AddConstraint(
            model_name='ligneachat',
            constraint=models.UniqueConstraint(fields=('achat', 'produit'), name='unique_produit_par_achat'),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.UniqueConstraint(fields=('magasin', 'numero_facture'), name='unique_vente_par_magasin'),
        ),
    ]
