# Generated by Django 6.0.2 on 2026-03-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0006_alter_achat_options_alter_achat_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
