# Generated by Django 6.0.2 on 2026-03-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0007_produit_date_expiration_produit_date_fabrication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur_primaire', models.CharField(default='#0d6efd', help_text='Couleur principale', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#6c757d', help_text='Couleur secondaire', max_length=7)),
                ('couleur_texte', models.CharField(default='#000000', help_text='Couleur texte', max_length=7)),
                ('couleur_fond', models.CharField(default='#ffffff', help_text='Couleur de fond', max_length=7)),
                ('couleur_sidebar', models.CharField(default='#1f2937', help_text='Sidebar', max_length=7)),
                ('couleur_header', models.CharField(default='#ffffff', help_text='Header', max_length=7)),
                ('couleur_bouton', models.CharField(default='#0d6efd', help_text='Bouton', max_length=7)),
                ('couleur_bouton_hover', models.CharField(default='#0b5ed7', help_text='Bouton au survol', max_length=7)),
                ('couleur_alert', models.CharField(default='#dc3545', help_text="Messages d'alerte", max_length=7)),
                ('couleur_success', models.CharField(default='#198754', help_text='Messages succès', max_length=7)),
                ('couleur_info', models.CharField(default='#0dcaf0', help_text='Messages info', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('mode_sombre', models.BooleanField(default=False)),
                ('devise', models.CharField(default='GNF', help_text="Devise de l'interface", max_length=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('magasin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='supermarcher.magasin')),
            ],
        ),
    ]
