# Generated by Django 6.0.2 on 2026-03-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0008_thememagasin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thememagasin',
            name='devise',
        ),
        migrations.AlterField(
            model_name='thememagasin',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='logos/'),
        ),
    ]
