# Generated by Django 6.0.2 on 2026-03-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0009_remove_thememagasin_devise_alter_thememagasin_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_alert',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_bouton',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_bouton_hover',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_fond',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_header',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_info',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_primaire',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_secondaire',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_sidebar',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_success',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='couleur_texte',
        ),
        migrations.RemoveField(
            model_name='thememagasin',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='thememagasin',
            name='couleur_principale',
            field=models.CharField(default='#16a34a', max_length=7),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='devise',
            field=models.CharField(default='GNF', max_length=10),
        ),
        migrations.AlterField(
            model_name='thememagasin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
