# Generated by Django 5.2.12 on 2026-03-15 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0010_remove_thememagasin_couleur_alert_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='achat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supermarcher.produit'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='quantite',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supermarcher.produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code_barre',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thememagasin',
            name='couleur_principale',
            field=models.CharField(default='#1324db', max_length=7),
        ),
        migrations.AlterField(
            model_name='thememagasin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('magasin', 'sku'), name='unique_sku_par_magasin'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('magasin', 'code_barre'), name='unique_code_barre_par_magasin'),
        ),
    ]
