# Generated by Django 5.2.12 on 2026-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('supermarcher', '0011_alter_produit_unique_together_alter_achat_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={},
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['magasin', 'date_creation'], name='supermarche_magasin_0fb0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['statut'], name='supermarche_statut_a15897_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['fournisseur'], name='supermarche_fournis_69882c_idx'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['magasin'], name='supermarche_magasin_2cafe2_idx'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['nom'], name='supermarche_nom_d9fef0_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['magasin'], name='supermarche_magasin_c2567e_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['nom'], name='supermarche_nom_4eaa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneachat',
            index=models.Index(fields=['achat'], name='supermarche_achat_i_6432de_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneachat',
            index=models.Index(fields=['produit'], name='supermarche_produit_a54eef_idx'),
        ),
        migrations.AddIndex(
            model_name='lignevente',
            index=models.Index(fields=['vente'], name='supermarche_vente_i_a86a97_idx'),
        ),
        migrations.AddIndex(
            model_name='lignevente',
            index=models.Index(fields=['produit'], name='supermarche_produit_80952e_idx'),
        ),
        migrations.AddIndex(
            model_name='magasin',
            index=models.Index(fields=['slug'], name='supermarche_slug_f4f7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='magasin',
            index=models.Index(fields=['proprietaire'], name='supermarche_proprie_7eaeea_idx'),
        ),
        migrations.AddIndex(
            model_name='magasin',
            index=models.Index(fields=['actif'], name='supermarche_actif_7d7718_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['magasin', 'produit'], name='supermarche_magasin_8a80bd_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='supermarche_type_mo_da5383_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['date_creation'], name='supermarche_date_cr_abc191_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['magasin', 'nom'], name='supermarche_magasin_5a1cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['magasin', 'categorie'], name='supermarche_magasin_6e8475_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['actif'], name='supermarche_actif_fd273b_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['date_creation'], name='supermarche_date_cr_a4761c_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['date_expiration'], name='supermarche_date_ex_498adc_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['magasin', 'code_barre'], name='supermarche_magasin_13998a_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['magasin', 'sku'], name='supermarche_magasin_516e50_idx'),
        ),
        migrations.AddIndex(
            model_name='thememagasin',
            index=models.Index(fields=['magasin'], name='supermarche_magasin_6feec9_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='supermarche_email_1089e7_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role'], name='supermarche_role_14a8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['magasin'], name='supermarche_magasin_a7afd1_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['magasin', 'date_creation'], name='supermarche_magasin_66080d_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['statut'], name='supermarche_statut_47fca2_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['mode_paiement'], name='supermarche_mode_pa_ed1a6a_idx'),
        ),
    ]
