# Generated by Django 5.2.12 on 2026-03-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0013_alter_achat_id_alter_categorie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='supermarcher.magasin'),
        ),
    ]
