# Generated by Django 5.2.12 on 2026-03-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0014_auditlog_magasin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('PRINT', 'Impression'), ('EXPORT', 'Export données'), ('LOGIN', 'Connexion'), ('LOGIN_FAILED_PASSWORD', 'Échec connexion (mot de passe)'), ('LOGIN_FAILED_UNKNOWN', 'Échec connexion (inconnu)'), ('LOGOUT', 'Déconnexion'), ('CANCEL', 'Annulation'), ('ACTIVATE', 'Activation'), ('DISABLE', 'Désactivation'), ('CUSTOM', 'Action métier')], max_length=50),
        ),
    ]
