# Generated by Django 5.2.12 on 2026-03-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0015_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='login_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
