# Generated by Django 5.2.12 on 2026-03-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarcher', '0016_auditlog_login_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
